[package]
name = "handterm-common"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = { workspace = true }
flate2 = "1.1"
png = "0.17"
mdwright-latex = "0.1.3"

[dev-dependencies]
bincode = { workspace = true }
